name: junitreport
version: 1.3.2-dev
description: Generate JUnit XML reports from dart test runs. Transforms the output of dart or flutter tests to
  JUnit style XML
publish_to: none

homepage: https://github.com/TOPdesk/dart-junitreport

dependencies:
  args:
  intl:
  testreport:
    path: ../testreport
  xml: 

dev_dependencies:
  flutter_lints:
  test:

environment:
  sdk: ">=2.14.0 <3.0.0"

executables:
  tojunit: