name: junitreport
version: 1.0.2-dev
description: Generate JUnit XML reports from dart test runs. Transforms the output of dart or flutter tests to
  JUnit style XML

authors:
- Roel Spilker <r.spilker@gmail.com>

homepage: https://github.com/TOPdesk/dart-junitreport
documentation:

dependencies:
  xml: '^3.3.1'
  intl: '^0.15.8'
  testreport: '^1.0.0'
  args: '^1.5.2'

dev_dependencies:
  test: any

environment:
  sdk: '>=2.1.0 <3.0.0'

executables:
  tojunit:
